version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: devpulse-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: devpulse
      POSTGRES_USER: devpulse
      POSTGRES_PASSWORD: devpulse_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - devpulse-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: devpulse-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - devpulse-network

  # DevPulse API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devpulse-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://devpulse:devpulse_password@postgres:5432/devpulse
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-this
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    networks:
      - devpulse-network

volumes:
  postgres_data:
  redis_data:

networks:
  devpulse-network:
    driver: bridge
