services:
  - type: web
    name: devpulse-api
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health

databases:
  - name: devpulse-db
    databaseName: devpulse
    user: devpulse
    plan: starter
